package Modelos;
// Generated 29/11/2017 10:23:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campeonatos generated by hbm2java
 */
public class Campeonatos  implements java.io.Serializable {


     private Integer idCampeonatos;
     private Establecimiento establecimiento;
     private String nombre;
     private String cupos;
     private String premiacion;
     private String maxEquipos;
     private String estado;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);
     private Set<Partido> partidos = new HashSet<Partido>(0);

    public Campeonatos() {
    }

	
    public Campeonatos(Establecimiento establecimiento, String nombre, String cupos, String premiacion, String maxEquipos, String estado) {
        this.establecimiento = establecimiento;
        this.nombre = nombre;
        this.cupos = cupos;
        this.premiacion = premiacion;
        this.maxEquipos = maxEquipos;
        this.estado = estado;
    }
    public Campeonatos(Establecimiento establecimiento, String nombre, String cupos, String premiacion, String maxEquipos, String estado, Set<Equipo> equipos, Set<Partido> partidos) {
       this.establecimiento = establecimiento;
       this.nombre = nombre;
       this.cupos = cupos;
       this.premiacion = premiacion;
       this.maxEquipos = maxEquipos;
       this.estado = estado;
       this.equipos = equipos;
       this.partidos = partidos;
    }
   
    public Integer getIdCampeonatos() {
        return this.idCampeonatos;
    }
    
    public void setIdCampeonatos(Integer idCampeonatos) {
        this.idCampeonatos = idCampeonatos;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCupos() {
        return this.cupos;
    }
    
    public void setCupos(String cupos) {
        this.cupos = cupos;
    }
    public String getPremiacion() {
        return this.premiacion;
    }
    
    public void setPremiacion(String premiacion) {
        this.premiacion = premiacion;
    }
    public String getMaxEquipos() {
        return this.maxEquipos;
    }
    
    public void setMaxEquipos(String maxEquipos) {
        this.maxEquipos = maxEquipos;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }




}


