package Modelos;
// Generated 29/11/2017 10:23:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cancha generated by hbm2java
 */
public class Cancha  implements java.io.Serializable {


     private Integer idCancha;
     private Establecimiento establecimiento;
     private String tipoCancha;
     private String estado;
     private String foto;
     private int valor;
   
     
     
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

    public Cancha() {
    }

	
    public Cancha(Establecimiento establecimiento, String tipoCancha, String estado, String foto, int valor) {
        this.establecimiento = establecimiento;
        this.tipoCancha = tipoCancha;
        this.estado = estado;
        this.foto = foto;
        this.valor = valor;
    }
    public Cancha(Establecimiento establecimiento, String tipoCancha, String estado, String foto, int valor, Set<Alquiler> alquilers) {
       this.establecimiento = establecimiento;
       this.tipoCancha = tipoCancha;
       this.estado = estado;
       this.foto = foto;
       this.valor = valor;
       this.alquilers = alquilers;
    }
   
    public Integer getIdCancha() {
        return this.idCancha;
    }
    
    public void setIdCancha(Integer idCancha) {
        this.idCancha = idCancha;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getTipoCancha() {
        return this.tipoCancha;
    }
    
    public void setTipoCancha(String tipoCancha) {
        this.tipoCancha = tipoCancha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


