package Modelos;
// Generated 29/11/2017 10:23:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Usuarios usuarios;
     private String nombre;
     private String apellido;
     private String documento;
     private long celular;
     private String estado;
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Cliente() {
    }

	
    public Cliente(Usuarios usuarios, String nombre, String apellido, String documento, long celular, String estado) {
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.apellido = apellido;
        this.documento = documento;
        this.celular = celular;
        this.estado = estado;
    }
    public Cliente(Usuarios usuarios, String nombre, String apellido, String documento, long celular, String estado, Set<Alquiler> alquilers, Set<Equipo> equipos) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.apellido = apellido;
       this.documento = documento;
       this.celular = celular;
       this.estado = estado;
       this.alquilers = alquilers;
       this.equipos = equipos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public long getCelular() {
        return this.celular;
    }
    
    public void setCelular(long celular) {
        this.celular = celular;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


