package Modelos;
// Generated 29/11/2017 10:23:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento  implements java.io.Serializable {


     private Integer idEstablecimiento;
     private Usuarios usuarios;
     private String nombre;
     private String nit;
     private String direccion;
     private long celular;
     private String foto;
     private int calificacion;
     private String estado;
     private String municipio;
     private Set<Campeonatos> campeonatoses = new HashSet<Campeonatos>(0);
     private Set<Cancha> canchas = new HashSet<Cancha>(0);

    public Establecimiento() {
    }

	
    public Establecimiento(Usuarios usuarios, String nombre, String nit, String direccion, long celular, String foto, int calificacion, String estado, String municipio) {
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.nit = nit;
        this.direccion = direccion;
        this.celular = celular;
        this.foto = foto;
        this.calificacion = calificacion;
        this.estado = estado;
        this.municipio = municipio;
    }
    public Establecimiento(Usuarios usuarios, String nombre, String nit, String direccion, long celular, String foto, int calificacion, String estado, String municipio, Set<Campeonatos> campeonatoses, Set<Cancha> canchas) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.nit = nit;
       this.direccion = direccion;
       this.celular = celular;
       this.foto = foto;
       this.calificacion = calificacion;
       this.estado = estado;
       this.municipio = municipio;
       this.campeonatoses = campeonatoses;
       this.canchas = canchas;
    }
   
    public Integer getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(Integer idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public long getCelular() {
        return this.celular;
    }
    
    public void setCelular(long celular) {
        this.celular = celular;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public Set<Campeonatos> getCampeonatoses() {
        return this.campeonatoses;
    }
    
    public void setCampeonatoses(Set<Campeonatos> campeonatoses) {
        this.campeonatoses = campeonatoses;
    }
    public Set<Cancha> getCanchas() {
        return this.canchas;
    }
    
    public void setCanchas(Set<Cancha> canchas) {
        this.canchas = canchas;
    }




}


