package Modelos;
// Generated 29/11/2017 10:23:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private String correo;
     private String contrasena;
     private String perfil;
     private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<SAdministrador> SAdministradors = new HashSet<SAdministrador>(0);

    public Usuarios() {
    }

	
    public Usuarios(String correo, String contrasena, String perfil) {
        this.correo = correo;
        this.contrasena = contrasena;
        this.perfil = perfil;
    }
    public Usuarios(String correo, String contrasena, String perfil, Set<Establecimiento> establecimientos, Set<Cliente> clientes, Set<SAdministrador> SAdministradors) {
       this.correo = correo;
       this.contrasena = contrasena;
       this.perfil = perfil;
       this.establecimientos = establecimientos;
       this.clientes = clientes;
       this.SAdministradors = SAdministradors;
    }
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Set<Establecimiento> getEstablecimientos() {
        return this.establecimientos;
    }
    
    public void setEstablecimientos(Set<Establecimiento> establecimientos) {
        this.establecimientos = establecimientos;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<SAdministrador> getSAdministradors() {
        return this.SAdministradors;
    }
    
    public void setSAdministradors(Set<SAdministrador> SAdministradors) {
        this.SAdministradors = SAdministradors;
    }




}


